"""Small output helpers shared by the recompiler CLI."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Iterable, Optional


def _write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="\n") as stream:
        json.dump(value, stream, indent=2, ensure_ascii=False)
        stream.write("\n")
    os.replace(temporary, path)


def write_summary(stats: dict, output_dir: str) -> str:
    """Write the recompiler statistics and return the output path."""
    path = Path(output_dir) / "summary.json"
    _write_json(path, stats)
    return str(path)


def print_stats(stats: dict) -> None:
    """Print translation statistics in a form suitable for CI logs."""
    total = stats.get("total", 0)
    translated = stats.get("translated", 0)
    failed = stats.get("failed", 0)
    print("\nRecompilation statistics:")
    print(f"  Functions:   {total:,d}")
    print(f"  Translated:  {translated:,d}")
    print(f"  Failed:      {failed:,d}")
    if "total_lines" in stats:
        print(f"  C lines:     {stats['total_lines']:,d}")
    if "output_size" in stats:
        print(f"  Output bytes: {stats['output_size']:,d}")
    if stats.get("unresolved_stubs"):
        print(f"  Stubbed call targets: {stats['unresolved_stubs']:,d}")
    if stats.get("manual_functions"):
        print(f"  Manual functions: {stats['manual_functions']:,d}")
    if stats.get("mmio_functions"):
        print(f"  MMIO functions: {stats['mmio_functions']:,d}")
    if stats.get("spin_loops"):
        print(f"  Spin loops: {stats['spin_loops']:,d}")
    unimplemented = stats.get("unimplemented") or {}
    if unimplemented:
        count = sum(len(values) if isinstance(values, list) else int(values)
                    for values in unimplemented.values())
        print(f"  Unimplemented instruction sites: {count:,d}")


def _function_name(address: int, function: dict) -> str:
    """Use the same stable name fallback as the translator."""
    name = function.get("name") or f"sub_{address:08X}"
    # Header mode is a source generator; avoid allowing a database name to
    # inject punctuation or a second declaration into the generated file.
    safe = "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in name)
    if not safe or safe[0].isdigit():
        safe = f"sub_{address:08X}"
    return safe


def generate_header(functions: Iterable, path: str,
                    abi_db: Optional[dict] = None,
                    title: Optional[str] = None) -> str:
    """Generate forward declarations for ``tools.recomp --header``.

    ``functions`` is the list of ``(address, function_info)`` pairs returned by
    ``BatchTranslator.get_functions_by_category``.  ABI details are comments
    only: all lifted functions intentionally share the register-model
    ``void(void)`` ABI at the C boundary.
    """
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    abi_db = abi_db or {}
    title = title or "Xbox Game"

    lines = [
        "/*",
        f" * {title} - Recompiled Function Declarations",
        " * Generated by tools/recomp; do not edit by hand.",
        " */",
        "",
        "#ifndef RECOMP_FUNCTIONS_H",
        "#define RECOMP_FUNCTIONS_H",
        "",
        '#include "recomp_types.h"',
        "",
    ]
    seen = set()
    for address, function in sorted(functions, key=lambda item: item[0]):
        address = int(address)
        name = _function_name(address, function)
        if name in seen:
            continue
        seen.add(name)
        abi = abi_db.get(address, {})
        convention = abi.get("calling_convention")
        suffix = f" /* {convention} */" if convention else ""
        lines.append(f"void {name}(void);  /* 0x{address:08X} */{suffix}")

    lines.extend(["", "#endif /* RECOMP_FUNCTIONS_H */", ""])
    temporary = destination.with_name(destination.name + ".tmp")
    temporary.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    os.replace(temporary, destination)
    return str(destination)
